/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        base: 'var(--color-bg-base)',
        chrome: 'var(--color-bg-chrome)',
        surface: 'var(--color-bg-surface)',
        elevated: 'var(--color-bg-elevated)',
        sunken: 'var(--color-bg-sunken)',
        overlay: 'var(--color-bg-overlay)',
        'surface-hover': 'var(--color-bg-hover)',
        'surface-active': 'var(--color-bg-active)',
        'border-default': 'var(--color-border-default)',
        'border-input': 'var(--color-border-input)',
        'divider': 'var(--color-divider)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted': 'var(--color-text-muted)',
        'text-faint': 'var(--color-text-faint)',
        'status-due-bg': 'var(--color-status-due-bg)',
        'status-due-border': 'var(--color-status-due-border)',
        'status-due-text': 'var(--color-status-due-text)',
        'status-success-bg': 'var(--color-status-success-bg)',
        'status-success-border': 'var(--color-status-success-border)',
        'status-success-text': 'var(--color-status-success-text)',
        'status-warn-bg': 'var(--color-status-warn-bg)',
        'status-warn-border': 'var(--color-status-warn-border)',
        'status-warn-text': 'var(--color-status-warn-text)',
        'status-info-bg': 'var(--color-status-info-bg)',
        'status-info-border': 'var(--color-status-info-border)',
        'status-info-text': 'var(--color-status-info-text)',
        'status-error-bg': 'var(--color-status-error-bg)',
        'status-error-border': 'var(--color-status-error-border)',
        'status-error-text': 'var(--color-status-error-text)',
        'status-orange-bg': 'var(--color-status-orange-bg)',
        'status-orange-text': 'var(--color-status-orange-text)',
        'status-purple-bg': 'var(--color-status-purple-bg)',
        'status-purple-text': 'var(--color-status-purple-text)',
        'status-amber-bg': 'var(--color-status-amber-bg)',
        'status-amber-border': 'var(--color-status-amber-border)',
        'status-amber-text': 'var(--color-status-amber-text)',
        'nav-active': 'var(--color-nav-active)',
        'nav-inactive': 'var(--color-nav-inactive)',
        'word-unrevealed': 'var(--color-word-unrevealed)',
        'word-incorrect': 'var(--color-word-incorrect)',
        'highlight': 'var(--color-highlight)',
      },
    },
  },
  plugins: [],
}
